/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    VuetifyProvider: typeof import('./src/components/VuetifyProvider.vue')['default']
  }
}
