/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToHome: typeof import('./src/components/BackToHome.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
  }
}
